### ISSUE TITLE
Pond is stuck on one frame on real devices, though functional on emulators

### ISSUE THREAD

**Issue by FlyOrBoom** [AHSAppDevTeam/Pomodoro-Study-App#7]
The pond with fish in it is stuck on one frame when the app is opened with an APK or with the ADB.

What did not work:
- Attempted replication: Downgrading the Android version of the virtual device to match the real one (5.1 Lollipop)
- Attempted fix: https://stackoverflow.com/questions/16460018/opengl-es-2-0-graphic-works-on-emulator-but-dont-work-on-real-device
- Attempted fix: Upgrading OpenGL ES library to 3.0

Possible points of failure:
- `SystemClock.elapsedRealtime` is frozen
- `GLSurfaceView.Renderer.onDrawFrame` isn't being called continuously
- `KoiShader` crashed after first frame

Notes:
- Exiting the aquarium view and creating a new one results in different fish patterns due to random seeds.

**Comment by jeffreyAaron** [comment]
I figured it out!
The fish is moving on the phone, it is just moving very slowly.
The gpu in the phone probably can't handle the graphics and render fast enough.
I have screen shots that prove this.

**Comment by jeffreyAaron** [comment]
Solution: Speed up the fish based on the frame rate

**Comment by FlyOrBoom** [comment]
Issue diverted by using WebGL/WebView
